#Nesta ponto do projeto é usado dados locais
#Futuramente irei configurar vai variaveis de ambiente 

var:
  ip:
    redis: 10.0.0.127
  
  port: 
    redis: 6379

  password:
    redis: 123456
    
    
userAdminPassword: "123456"


jwt:
  private:
    key: classpath:private.key
  
  public:
    key: classpath:public.key


server:
  error:
    include-stacktrace : never


spring:
  application:
    name: "app"
  datasource:
      url: jdbc:mysql://10.0.0.127:3306/GasDataBase?allowPublicKeyRetrieval=true
      username: root
      password: 123456

  jpa:
      hibernate:
          ddl-auto: update

      show-sql: true

      defer-datasource-initialization: true

      init:
        mode: always
    
management:
  endpoints:
    web:
      exposure:
        include: "*"
